### ISSUE TITLE
Limit changefeed per client

### ISSUE THREAD

**Issue by schwamster** [schwamster/doc-store#6]

**Comment by schwamster** [comment]
➤ Andrei commented:
I have noticed that the "client" property of a Document in doc-store is a string; I thought initially it would make sense to listen to DB changes "per client" so that a client isnt notified by changes of other clients, but I think, what I understand by client, is not what you intended it, since its a string; what does client actually mean, can you give me an example  so taht I know if what I want to implement even makes sense? thank youi

**Comment by schwamster** [comment]
➤ Bastian commented:
Client was meant to be a 'mandant'. So many users belong to one client.

**Comment by andreimcristof** [comment]
Then it's how i thought it was intended, and notifications limited per client makes sense, thank you

On December 12, 2016 5:35:52 AM GMT+01:00, Bastian <notifications@github.com> wrote:
>➤ Bastian commented:
>Client was meant to be a 'mandant'. So many users belong to one client.
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/schwamster/doc-store/issues/6#issuecomment-266341427

-- 
Sent from my Android device with K-9.

**Comment by schwamster** [comment]
➤ Andrei commented:
ah this is a bit more difficult than i thought initially, since i dont have the information which client that request was made for; ideally, that comes in the request headers token or something. then i know what client i need to start the changefeeds for. 

not entirely sure if this is the ideal handling, will have to do more research.

**Comment by schwamster** [comment]
➤ Bastian commented:
I am working on exactly that right now. As soon as I have a basic identity thing going u will have that info as a claim

**Comment by andreimcristof** [comment]
Cool ! Pls let me know if i can help with this topic. 
Btw a small offtopic: just realised today that instead of asking for branch create permisisons on all these repos, I shouldve actually used the "fork and branch" workflow.... was wondering why I can merge my own stuff. Feel free to revoke branch rights if you wish, i will use forks afterwards then

**Comment by schwamster** [comment]
➤ Bastian commented:
do that as u please, u are a collaborator after all

**Comment by andreimcristof** [comment]
I just read and learned the diff between collaborators and contributors, thank you for pointing that out

**Comment by andreimcristof** [comment]
solved with PR schwamster/doc-store/pull/10

this is all experimental WIP, it might that we won't use it that way and just let the store notify of all changes, and then the notification api actually decides whom to notify and whom to not;
